# MySQL 数据库基础配置
host = "127.0.0.1"
port = 3306
username = "root"
password = "password"
database = "test_db"
charset = "utf8mb4"
echo = false
pool_size = 5
max_overflow = 10
pool_timeout = 30
pool_recycle = 1800
pool_pre_ping = true

